config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  scope module: :public do
    root to: "homes#top"
    get '/about' => 'homes#about'
    resources :items, only: [:index, :show]
    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get 'customers/confirm' => 'customers#confirm'
    patch 'customers/withdraw' => 'customers#withdraw'
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all'
      end
    end
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm'
        get 'complete'
      end
    end
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  # 管理者用
  namespace :admin do
    root to: "homes#top"
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  has_one_attached :image
  

  def subtotal
    item.with_tax_price * amount
  end
  
  def get_image(width, hight)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, hight]).processed
  end
  
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  
  def customer_address_display
    '〒' + postal_code + ' ' + address + ' ' + last_name + first_name
  end
  
  enum is_deleted: { deleted: true, undeleted: false } 
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image

  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre

  def get_image(width, hight)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no-image.png')
      image.attach(io: File.open(file_path), filename: 'no-image.png', content_type: 'image/png')
    end
    image.variant(resize_to_limit: [width, hight]).processed
  end

  enum is_active: { sale: true, stop_selling: false }

  def with_tax_price
    (price*1.1).floor
  end

  validates :name, presence: true
  validates :introduction, presence: true
  validates :genre_id, presence: true
  validates :price, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :customer

  enum payment_way: { credit_card: 0, transfer: 1 }
  enum status: { waiting_for_payment: 0, payment_confirmation: 1, production: 2, shipping_preparation: 3, sent: 4 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order
  
  def subtotal
    item.with_tax_price * amount
  end
  
  enum making_status: { unproduced: 0, waiting_for_production: 1, production: 2, production_complete: 3 }

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customers_path
    else
      render :edit
    end
  end
  
  private
  
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, :is_deleted)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def new
    @genre = Genre.new
  end
  
  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to edit_admin_genre_path(@genre.id)
    else
      @genre = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end
  
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      @item = Item.all
      render new_admin_item_path
    end
  end

  def index
    @items = Item.page(params[:page])

  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_items_path
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :image, :genre_id)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @customer = Customer.find(@order.customer_id)
    @postage = 800
  end

  def update
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: params[:id])
    if @order.update(order_params)
      @order_details.update_all(making_status: 1) if @order.status == "payment_confirmation"
    end
    redirect_to admin_order_path
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-8">
      <h4 class="ml-5 mb-5"><%= @customer.last_name+@customer.first_name %>さんの会員情報編集</h4>
      <%= form_with model: @customer, url: admin_customer_path do |f| %>
      <table class="table table-borderless table-sm" >
        <tr>
          <th><%= f.label "会員ID" %></th>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <th><%= f.label "氏名" %></th>
          <td>
            <%= f.text_field :last_name %>
            <%= f.text_field :first_name, class:"ml-4" %>
          </td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <th><%= f.label "フリガナ" %></th>
          <td>
            <%= f.text_field :last_name_kana %>
            <%= f.text_field :first_name_kana, class:"ml-4" %>
          </td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <th><%= f.label "郵便番号" %></th>
          <td><%= f.text_field :postal_code %></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <th><%= f.label "住所" %></th>
          <td colspan="3"><%= f.text_field :address, class:"col-12" %></td>
        </tr>
        <tr>
          <th><%= f.label "電話番号" %></th>
          <td><%= f.text_field :telephone_number %></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <th><%= f.label "メールアドレス" %></th>
          <td><%= f.text_field :email %></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <th><%= f.label "会員ステータス" %></th>
          <td>
            <%= f.radio_button :is_deleted, "undeleted", style: "accent-color:black;" %>
            <%= f.label :is_deleted, "有効", value: false %>
            <%= f.radio_button :is_deleted, "deleted" , style: "accent-color:black;" %>
            <%= f.label :is_deleted, "退会", value: true %>
          </td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <th></th>
          <td><%= f.submit "変更を保存", url: admin_customers_path, method: :patch, class:"btn btn-success" %></td>
          <td></td>
          <td></td>
        </tr>
      </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-2"></div>
    <div class="col-8">
      <h4 class="ml-3 mb-5">会員一覧</h4>
      <table class="ml-5 table table-borderless col-12">
        <tr>
          <th class="col-1">会員ID</th>
          <th class="col-2">氏名</th>
          <th class="col-2">メールアドレス</th>
          <th class="col-3">ステータス</th>
        </tr>
      <% @customers.each do |customers| %>
        <tr>
          <td><%= customers.id %></td>
          <td>
            <%= link_to admin_customer_path(customers.id), class:"border-bottom", :style=>"color:black;" do %>
              <%= customers.last_name+customers.first_name %>
            <% end %>
          </td>
          <td><%= customers.email %></td>
          <td class="<%= "text-success" if customers.is_deleted == "undeleted" %><%= "text-muted" if customers.is_deleted == "deleted" %>"><%= customers.is_deleted_i18n %></td>
        </tr>
      <% end %>
      </table>
      <%= paginate @customers %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-10">
      <h4 class="ml-5 mb-5"><%= @customer.last_name+@customer.first_name %>さんの会員情報</h4>
      <table class="table table-borderless table-sm">
        <tr>
          <th class="co-1">会員ID</th>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <th class="co-1">氏名</th>
          <td>
            <%= @customer.last_name %>
            <%= @customer.first_name %>
          </td>
        </tr>
        <tr>
          <th class="co-1">フリガナ</th>
          <td>
            <%= @customer.last_name_kana %>
            <%= @customer.first_name_kana %>
          </td>
        </tr>
        <tr>
          <th class="co-1">郵便番号</th>
          <td><%= @customer.postal_code %></td>
        </tr>
        <tr>
          <th class="co-1">住所</th>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <th class="co-1">電話番号</th>
          <td><%= @customer.telephone_number %></td>
        </tr>
        <tr>
          <th class="co-1">メールアドレス</th>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <th class="co-1">会員ステータス</th>
          <td class="<%= "text-success" if @customer.is_deleted == "undeleted" %><%= "text-muted" if @customer.is_deleted == "deleted" %>"><%= @customer.is_deleted_i18n %></td>
        </tr>
        <tr>
          <th class="co-1"></th>
          <td><%= link_to "編集する", edit_admin_customer_path, class:"btn btn-success col-2" %>
              <%= link_to "注文履歴一覧を見る", admin_root_path, class:"btn btn-primary ml-5" %></td>
        </tr>
      </table>
    </div>
  </div>
</div>