config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  scope module: :public do
    root to: "homes#top"
    get '/about' => 'homes#about'
    resources :items, only: [:index, :show]
    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get 'customers/confirm' => 'customers#confirm'
    patch 'customers/withdraw' => 'customers#withdraw'
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all'
      end
    end
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm'
        get 'complete'
      end
    end
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  # 管理者用
  namespace :admin do
    root to: "homes#top"
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  has_one_attached :image
  

  def subtotal
    item.with_tax_price * amount
  end
  
  def get_image(width, hight)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, hight]).processed
  end
  
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  
  def customer_address_display
    '〒' + postal_code + ' ' + address + ' ' + last_name + first_name
  end
  
  enum is_deleted: { deleted: true, undeleted: false } 
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image

  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre

  def get_image(width, hight)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no-image.png')
      image.attach(io: File.open(file_path), filename: 'no-image.png', content_type: 'image/png')
    end
    image.variant(resize_to_limit: [width, hight]).processed
  end

  enum is_active: { sale: true, stop_selling: false }

  def with_tax_price
    (price*1.1).floor
  end

  validates :name, presence: true
  validates :introduction, presence: true
  validates :genre_id, presence: true
  validates :price, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :customer

  enum payment_way: { credit_card: 0, transfer: 1 }
  enum status: { waiting_for_payment: 0, payment_confirmation: 1, production: 2, shipping_preparation: 3, sent: 4 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order
  
  def subtotal
    item.with_tax_price * amount
  end
  
  enum making_status: { unproduced: 0, waiting_for_production: 1, production: 2, production_complete: 3 }

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def new
    @genre = Genre.new
  end
  
  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to edit_admin_genre_path(@genre.id)
    else
      @genre = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end
  
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      @item = Item.all
      render new_admin_item_path
    end
  end

  def index
    @items = Item.page(params[:page])

  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_items_path
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :image, :genre_id)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @customer = Customer.find(@order.customer_id)
    @postage = 800
  end

  def update
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: params[:id])
    if @order.update(order_params)
      @order_details.update_all(making_status: 1) if @order.status == "payment_confirmation"
    end
    redirect_to admin_order_path
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end

end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
   def new
     super
   end

  # POST /resource/sign_in
   def create
     super
   end

  # DELETE /resource/sign_out
   def destroy
     super
   end

   def after_sign_out_path_for(resource)
      new_admin_session_path
   end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h4 class="ml-5 mb-5">ジャンル編集</h4>
      <%= form_with model: @genre, url: admin_genre_path do |f| %>
      <table>
        <tr>
          <th class="pr-5">ジャンル名</th>
          <td><%= f.text_field :name, class:"col-12" %></td>
          <td><%= f.submit "変更を保存", url: admin_genre_path, method: :patch, class:"btn btn-success ml-5 col-10" %></td>
        </tr>
      </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<h4 class="ml-5 mb-5">ジャンル一覧・追加</h4>
<div class="container float-left">
  <div class="row">
    <div class="col-8">
      <%= form_with model: @genre, url: admin_genres_path do |f| %>
  <table class="mb-5">
    <tr>
      <th><%= f.label "ジャンル名", class:"mr-5" %></th>
      <td><%= f.text_field :name, class:"col-12" %></td>
      <td><%= f.submit "新規登録", class:"btn btn-success ml-5" %></td>
    </tr>
  </table>
<% end %>
    </div>
  </div>
</div>

<table class="table mt-5">
  <tr>
    <th class="pl-5">ジャンル</th>
    <th></th>
  </tr>
  <% @genres.each do |genres| %>
    <tr>
      <td class="col-2"><%= genres.name %></td>
      <td><%= link_to "編集する", edit_admin_genre_path(genres.id), class:"btn btn-success" %></td>
    </tr>
  <% end %>
</table>

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-10">
      <h4 class="ml-5 mb-5">商品編集</h4>
      <div class="d-flex">
      <div class="col-2"></div>
      <%= form_with model: @item, url: admin_item_path do |f| %>
      <table class="col-12">
          <tr>
            <th><%= f.label "商品画像" %></th>
            <td><%= f.file_field :image, accept: "image/*", class:"form-control-field" %></td>
          </tr>
          <tr>
            <th><%= f.label "商品名" %></th>
            <td><%= f.text_field :name, class:"form-control" %></td>
          </tr>
          <tr>
            <th><%= f.label "商品説明" %></th>
            <td><%= f.text_area :introduction, class:"form-control" %></td>
          </tr>
          <tr>
            <th><%= f.label "ジャンル" %></th>
            <td><%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name), class:"custom-select col-12" %></td>
          </tr>
          <tr>
            <th><%= f.label "税抜価格" %></th>
            <td><%= f.text_field :price, class:"form-control" %></td>
            <td style="line-height:48px;">円</td>
          </tr>
          <tr class="text-align-left">
            <th><%= f.label "販売ステータス" %></th>
            <td class="text-align-left">
              <%= f.radio_button :is_active, "sale", style: "accent-color:black;" %>
              <%= f.label :is_active, "販売中", value: true %>
              <%= f.radio_button :is_active, "stop_selling", class:"ml-5", style: "accent-color:black;" %>
              <%= f.label :is_active, "販売停止中", value: false %>
            </td>
          </tr>
      </table>
      <p class="text-center"><%= f.submit "変更を保存", url: admin_items_path, method: :patch, class:"btn btn-success" %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h4 class="ml-5">商品一覧</h4>
      <div class="d-flex">
        <p class="ml-auto"><%= link_to "＋", new_admin_item_path, class: "font-weight-bold btn btn-light rounded-circle shadow p-0", style: "font-size:25px;width:3rem;height:3rem;text-align:center;line-height:48px;" %></p>
      </div>
      <table class="table table-borderless">
        <tr>
          <th class="col-1">商品ID</th>
          <th class="col-3">商品名</th>
          <th class="col-1">税抜価格</th>
          <th class="col-3">ジャンル</th>
          <th class="col-1">ステータス</th>
        </tr>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td>
            <%= link_to admin_item_path(item.id), class:"border-bottom", :style=>"color:black;" do %>
              <%= item.name %>
            <% end %>
          </td>
          <td><%= (item.price).to_s(:delimited) %></td>
          <td><%= item.genre.name %></td>
          <td class="<%= "text-success" if item.is_active == "sale" %><%= "text-muted" if item.is_active == "stop_selling" %>"><%= item.is_active_i18n %></td>
        </tr>
      <% end %>
      </table>
      <%= paginate @items %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-10">
      <h4 class="ml-5 mb-5">商品新規登録</h4>
      <div class="d-flex">
      <div class="col-2"></div>
      <%= form_with model: Item.new, url: admin_items_path do |f| %>
      <table class="col-12">
          <tr>
            <th><%= f.label "商品画像" %></th>
            <td><%= f.file_field :image, accept: "image/*", class:"form-control-field" %></td>
          </tr>
          <tr>
            <th><%= f.label "商品名" %></th>
            <td><%= f.text_field :name, class:"form-control" %></td>
          </tr>
          <tr>
            <th><%= f.label "商品説明" %></th>
            <td><%= f.text_area :introduction, class:"form-control" %></td>
          </tr>
          <tr>
            <th><%= f.label "ジャンル" %></th>
            <td><%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name), { include_blank: "--選択してください--" }, class:"custom-select col-12" %></td>
          </tr>
          <tr>
            <th><%= f.label "税抜価格" %></th>
            <td><%= f.text_field :price, class:"form-control"%></td>
            <td style="line-height:48px;">円</td>
          </tr>
          <tr class="text-align-left">
            <th><%= f.label "販売ステータス" %></th>
            <td class="text-align-left">
              <%= f.radio_button :is_active, "sale", style: "accent-color:black;" %>
              <%= f.label :is_active, "販売中", value: true %>
              <%= f.radio_button :is_active, "stop_selling", class:"ml-5", style: "accent-color:black;" %>
              <%= f.label :is_active, "販売停止中", value: false %>
            </td>
          </tr>
      </table>
        <p class="text-center"><%= f.submit "新規登録", url: admin_items_path, method: :post, class:"btn btn-success col-3" %></p>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h4 class="ml-5 mb-5">商品詳細</h4>
      <div class="d-flex">
        <div><%= image_tag @item.get_image(200, 300) %></div>
        <table class="ml-5 table table-borderless table-sm">
          <tr>
            <td class="col-2">商品名</td>
            <td><%= @item.name %></td>
          </tr>
          <tr>
            <td class="col-2">商品説明</td>
            <td><%= @item.introduction %></td>
          </tr>
          <tr>
            <td class="col-2">ジャンル</td>
            <td><%= @item.genre.name %></td>
          </tr>
          <tr>
            <td class="col-2">税込価格<br/>(税抜価格)</td>
            <td style="line-height:50px;"><%= (@item.price*1.1).round.to_s(:delimited) %>(<%= @item.price.to_s(:delimited) %>)円</td>
          <tr>
            <td class="col-2">販売ステータス</td>
            <td class="<%= "text-success" if @item.is_active == "sale" %><%= "text-muted" if @item.is_active == "stop_selling" %>">
              <h5><%= @item.is_active_i18n %></h5>
            </td>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>
<div class="container text-center">
  <%= link_to "編集する", edit_admin_item_path, class:"btn btn-success btn-lg col-2" %>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h4 class="ml-5 mb-5">注文履歴詳細</h4>
      <%= form_with model: @order, url: admin_order_path do |f| %>
      <table class="table table-borderless">
        <tr>
          <th class="col-2">購入者</th>
          <td>
            <%= link_to admin_customer_path(@customer.id), class:"border-bottom", :style=>"color:black;" do %>
              <%= @customer.last_name + @customer.first_name %>
            <% end %>
          </td>
        </tr>
        <tr>
          <th class="col-2">注文日</th>
          <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
        </tr>
        <tr>
          <th class="col-2">配送先</th>
          <td>
            <%= "〒" + @order.post_code %>
            <%= @order.address %></br>
            <%= @order.name %>
          </td>
        </tr>
        <tr>
          <th class="col-2">支払い方法</th>
          <td><%= @order.payment_way_i18n %></td>
        </tr>
        <tr>
          <th class="col-2">注文ステータス</th>
            <td>
              <%= f.select :status, Order.statuses.keys.map{|k|[t("enums.order.status.#{k}"),k]}, class:"custom-select" %>
              <%= f.submit '更新', method: :patch, class:"btn btn-success btn-sm ml-5" %>
            </td>
        </tr>
      </table>
      <% end %>
      <div class="d-flex">
        <table class="table table-borderless col-8">
          <tr>
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
          </tr>
          <% @order.order_details.each do |order_detail| %>
          <tr>
            <td>
              <%= order_detail.item.name %>
            </td>
            <td><%= (order_detail.price).to_s(:delimited) %></td>
            <td><%= order_detail.amount %></td>
            <% @subtotal = 0 %>
            <td><%= (order_detail.subtotal).to_s(:delimited) %></td>
            <% @subtotal += order_detail.subtotal %>
            <td>
            <%= form_with model: order_detail, url: admin_order_detail_path(order_detail.id) do |f| %>
              <%= f.select :making_status, OrderDetail.making_statuses.keys.map{|k|[t("enums.order_detail.making_status.#{k}"),k]}, class:"custom-select" %>
              <%= f.submit '更新', method: :patch, class:"btn btn-success btn-sm ml-5" %>
            <% end %>
            </td>
          </tr>
          <% end %>
        </table>
        <div class="col-1"></div>
        <table class="table table-borderless table-sm col-3">
          <% @total = 0 %>
            <% @order.order_details.each do |order_detail| %>
            <% @total += order_detail.subtotal %>
          <% end %>
          <tr>
            <th></th>
            <td></td>
          </tr>
          <tr>
            <th></th>
            <td></td>
          </tr>
          <tr>
            <th></th>
            <td></td>
          </tr>
          <tr>
            <th></th>
            <td></td>
          </tr>
          <tr>
            <th class="col-4">商品合計</th>
            <td class="col-1" align="center"><%= @total.to_s(:delimited) %>円</td>
          </tr>
          <tr>
            <th class="col-4">送料</th>
            <td class="col-1" align="center"><%= @postage %>円</td>
          </tr>
          <tr>
            <th class="col-4">請求金額合計</th>
            <td class="col-1" align="center">
              <%= (@total + @postage).to_s(:delimited) %>円
            </td>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>