config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  scope module: :public do
    root to: "homes#top"
    get '/about' => 'homes#about'
    resources :items, only: [:index, :show]
    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get 'customers/confirm' => 'customers#confirm'
    patch 'customers/withdraw' => 'customers#withdraw'
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all'
      end
    end
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm'
        get 'complete'
      end
    end
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  # 管理者用
  namespace :admin do
    root to: "homes#top"
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  has_one_attached :image
  

  def subtotal
    item.with_tax_price * amount
  end
  
  def get_image(width, hight)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, hight]).processed
  end
  
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  
  def customer_address_display
    '〒' + postal_code + ' ' + address + ' ' + last_name + first_name
  end
  
  enum is_deleted: { deleted: true, undeleted: false } 
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image

  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre

  def get_image(width, hight)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no-image.png')
      image.attach(io: File.open(file_path), filename: 'no-image.png', content_type: 'image/png')
    end
    image.variant(resize_to_limit: [width, hight]).processed
  end

  enum is_active: { sale: true, stop_selling: false }

  def with_tax_price
    (price*1.1).floor
  end

  validates :name, presence: true
  validates :introduction, presence: true
  validates :genre_id, presence: true
  validates :price, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :customer

  enum payment_way: { credit_card: 0, transfer: 1 }
  enum status: { waiting_for_payment: 0, payment_confirmation: 1, production: 2, shipping_preparation: 3, sent: 4 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order
  
  def subtotal
    item.with_tax_price * amount
  end
  
  enum making_status: { unproduced: 0, waiting_for_production: 1, production: 2, production_complete: 3 }

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def new
    @genre = Genre.new
  end
  
  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to edit_admin_genre_path(@genre.id)
    else
      @genre = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end
  
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      @item = Item.all
      render new_admin_item_path
    end
  end

  def index
    @items = Item.page(params[:page])

  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_items_path
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :image, :genre_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <header class="border-bottom border-dark border-3" >
      <nav class="navbar navbar-expand-1g navbar-light">
        <div>
          <a class="navbar-brand p-3" ><%= image_tag'logo.png', size: "200x60" %></a>
        </div>
        <div class="text-right">
        <ul class="navbar-nav list-group-horizontal" >
          <% if admin_signed_in? %>
          <li class="nav-item mr-5">
            <%= link_to "商品一覧", admin_items_path, class:"btn btn-light" %>
          </li>
          <li class="nav-item mr-5">
            <%= link_to "会員一覧", admin_customers_path, class:"btn btn-light" %>
          </li>
          <li class="nav-item mr-5">
            <%= link_to "注文履歴一覧", admin_root_path, class:"btn btn-light" %>
          </li>
          <li class="nav-item mr-5">
            <%= link_to "ジャンル一覧", admin_genres_path, class:"btn btn-light" %>
          </li>
          <li class="nav-item mr-5">
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:"btn btn-light" %>
          </li>
          <% elsif customer_signed_in? %>
          <div class="mr-5">
          ようこそ、
            <%= current_customer.last_name %>
            さん！
          </div>
          <li class="nav-item mr-5">
            <%= link_to "マイページ", customers_my_page_path, class:"btn btn-light" %>
          </li>
          <li class="nav-item mr-5">
            <%= link_to "商品一覧", items_path, class:"btn btn-light" %>
          </li>
          <li class="nav-item mr-5">
            <%= link_to "カート", cart_items_path, class:"btn btn-light" %>
          </li>
          <li class="nav-item mr-5">
            <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class:"btn btn-light" %>
          </li>
          <% else %>
          <li class="nav-item mr-5">
            <%= link_to "About", about_path, class:"btn btn-light" %>
          </li>
          <li class="nav-item mr-5">
            <%= link_to "商品一覧", items_path, class:"btn btn-light" %>
          </li>
          <li class="nav-item mr-5">
            <%= link_to "新規登録", new_customer_registration_path, class:"btn btn-light" %>
          </li>
          <li class="nav-item mr-5">
            <%= link_to "ログイン", new_customer_session_path, class:"btn btn-light" %>
          </li>
          <% end %>
        </ul>
        </div>
      </nav>
    </header>
    <main class="m-5">
    <%= yield %>
    </main>
    <footer class="border-top border-dark border-3 mt-auto">
      <div>　　</div>
    </footer>
  </body>
</html>